### ISSUE TITLE
конструктор требует непонятный мне аргумент

### ISSUE THREAD

**Issue by sergsemenov** [sergsemenov/3.4AfishaManager#1]
Больше нет сил на нее. Две недели, и какая-то засада, что с первой, что со второй. Ничего не понимаю, похоже, с объявлениями переменных, конструкторов, их полей всякого. Первую задачу кое-как сделал, сначала с if-ами мучился, потом пытался прикрутить проверку массивов разных размеров, что так и не решил =(. Во второй задаче вымучил ветку, но она отказалась работать на первом же тесте репозитория. Требует аргумент в конструктор, который в первой задаче отрабатывал:

Error:(9, 37) java: constructor AfishaManager in class ru.netology.domain.AfishaManager cannot be applied to given types;
  required: ru.netology.repository.AfishaRepository
  found: no arguments
  reason: actual and formal argument lists differ in length

Я просто уже сдаюсь. Прошу помочь с кодом. 

[ссылка на проблемный конструктор](https://github.com/sergsemenov/3.4AfishaManager/blob/073db3550dba18ee741913431802b6a35f1cbfb2/src/test/java/ru/netology/repository/AfishaRepositoryTest.java#L11)

@coursar

**Comment by coursar** [comment]
Так проблема не в репозитории, а в менеджере. Вы туда не кладёте репозиторий.
